name: survey_kit
description: Create beautiful surveys with Flutter (inspired by iOS ResearchKit Surveys)
version: 1.0.0-dev.3
homepage: https://quickbirdstudios.com
repository: https://github.com/quickbirdstudios/survey_kit
issue_tracker: https://github.com/quickbirdstudios/survey_kit/issues

flutter:
  plugin:
    platforms:
      android:
        package: com.quickbirdstudios.survey_kit
        pluginClass: SurveyKitPlugin
      ios:
        pluginClass: SurveyKitPlugin

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.3.0"
#  sdk: ">=2.17.0 <3.0.0"
#  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  chewie: ^1.8.5
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.3+2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.41
  lottie: ^3.1.3
  rxdart: ^0.28.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

