name: survey_kit
description: Create beautiful surveys with Flutter (inspired by iOS ResearchKit Surveys)
version: 1.0.0-dev.3
homepage: https://quickbirdstudios.com
repository: https://github.com/quickbirdstudios/survey_kit
issue_tracker: https://github.com/quickbirdstudios/survey_kit/issues

flutter:
  plugin:
    platforms:
      android:
        package: com.quickbirdstudios.survey_kit
        pluginClass: SurveyKitPlugin
      ios:
        pluginClass: SurveyKitPlugin

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  chewie: ^1.7.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter_markdown: ^0.6.18+3
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.36
  lottie: ^3.0.0
  rxdart: ^0.27.7
  universal_html: ^2.2.4
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  video_player: ^2.8.2
  visibility_detector: ^0.4.0+2
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

