name: survey_kit
description: Create beautiful surveys with Flutter (inspired by iOS ResearchKit Surveys)
version: 1.0.0-dev.3
homepage: https://quickbirdstudios.com
repository: https://github.com/quickbirdstudios/survey_kit
issue_tracker: https://github.com/quickbirdstudios/survey_kit/issues

flutter:
  plugin:
    platforms:
      android:
        package: com.quickbirdstudios.survey_kit
        pluginClass: SurveyKitPlugin
      ios:
        pluginClass: SurveyKitPlugin

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  chewie: ^1.7.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.17
  image_picker: ^1.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  just_audio: ^0.9.34
  lottie: ^2.5.0
  rxdart: ^0.27.7
  universal_html: ^2.2.3
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  video_player: ^2.7.0
  visibility_detector: ^0.4.0+2
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

